variable "default" {}
variable "devices" {}
variable "dns" {}
variable "routers" {}
variable "servers_mac" {}
variable "servers_proxmox" {}
variable "tags" {}
variable "terraform" {}
variable "vms_mac" {}
variable "vms_oci" {}
variable "vms_proxmox" {}
variable "websites" {}
