variable "cloudflare" {}
variable "github" {}
variable "oci" {}
variable "openwrt" {}
variable "proxmox" {}
variable "root_domain" {}
variable "root_email" {}
variable "routers" {}
variable "servers" {}
variable "virtual_machines" {}
variable "websites" {}
