networks:
  default:
    external: true
    name: docker
services:
  agent:
    image: portainer/agent
    ports:
      - 9001:9001
    restart: unless-stopped
    volumes:
      - /:/host
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
