#cloud-config
groups: ${jsonencode(server.user.groups)}
hostname: ${server.name}
locale: ${server.config.locale}
package_reboot_if_required: true
package_update: true
package_upgrade: true
packages: ${jsonencode(server.config.packages)}
ssh_pwauth: false
timezone: ${server.config.timezone}
runcmd:
%{ for init_command in init_commands ~}
  - ${init_command}
%{ endfor ~}
%{ if contains(server.config.packages, "qemu-guest-agent") ~}
  - systemctl enable --now qemu-guest-agent
%{ endif ~}
users:
  - name: ${server.user.username}
    gecos: ${server.user.fullname}
    groups: ${jsonencode(server.user.groups)}
    hashed_passwd: ${password_hash}
    lock_passwd: false
    shell: ${server.config.shell}
    ssh_authorized_keys: ${jsonencode(ssh_keys)}
write_files:
%{ if contains(server.flags, "ubuntu") ~}
  - path: /etc/networkd-dispatcher/routable.d/50-network
    permissions: "0755"
    content: |
      #!/bin/sh
      ethtool -K $(ip -o route get 1.1.1.1 | cut -d " " -f 5) rx-gro-list off rx-udp-gro-forwarding on
%{ endif ~}
  - path: /etc/sysctl.d/50-network.conf
    content: |
      net.core.rmem_max=8388608
      net.core.wmem_max=8388608
      net.ipv4.conf.all.forwarding=1
      net.ipv6.conf.all.forwarding=1
