#cloud-config
hostname: ${server.name}
locale: ${server.config.locale}
package_reboot_if_required: true
package_update: true
package_upgrade: true
ssh_pwauth: false
timezone: ${server.config.timezone}
%{ if length(server.user.groups) > 0 ~}
groups:
%{ for group in server.user.groups ~}
  - ${group}
%{ endfor ~}
%{ endif ~}
%{ if length(server.config.packages) > 0 ~}
packages:
%{ for package in server.config.packages ~}
  - ${package}
%{ endfor ~}
%{ endif ~}
%{ if contains(server.config.packages, "qemu-guest-agent") || length(init_commands) > 0 ~}
runcmd:
%{ for init_command in init_commands ~}
  - ${init_command}
%{ endfor ~}
%{ if contains(server.config.packages, "qemu-guest-agent") ~}
  - systemctl enable --now qemu-guest-agent
%{ endif ~}
%{ endif ~}
user:
  - gecos: ${server.user.fullname}
    groups: ${jsonencode(server.user.groups)}
    hashed_passwd: ${password_hash}
    lock_passwd: false
    name: ${server.user.username}
    ssh_authorized_keys: ${jsonencode(ssh_keys)}
write_files:
  - path: /etc/sysctl.d/net_forwarding.conf
    content: |
      net.core.rmem_max=8388608
      net.core.wmem_max=8388608
      net.ipv4.conf.all.forwarding=1
      net.ipv6.conf.all.forwarding=1
  - path: /etc/systemd/network/50-device-defaults.link
    content: |
      [Link]
      GRO=off
      UDPGROForwarding=on
  - path: /etc/systemd/network/50-tailscale.network
    content: |
      [Match]
      Name=tailscale*

      [Link]
      Unmanaged=yes
